#!/bin/sh

find /service -mindepth 1 -maxdepth 1 -type d | \
while read sv
do
	if [ -d ${sv}/log ]
	then
		continue
	else
		mkdir -p ${sv}/log
		cat << EOF > ${sv}/log/run
#!/bin/sh
exec svlogd -tt .
EOF
	fi
done

find /service -type f -exec chmod +x {} \+

if [ -z "$1" ]
then
	runsvdir -P /service
else
	runsvdir -P /service &
	exec $@
fi
